{% set name = "dtool_lookup_server_notification_plugin" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-lookup-server-notification-plugin/dtool-lookup-server-notification-plugin-{{ version }}.tar.gz
  sha256: 1986ca2dbe09145f536088e9c80f6446eecd2010ece5153c46007177ea12a5c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - dtool_lookup_server >=0.17.2
    - dtoolcore >=3.17.0
    - python >=3.6
    - markupsafe <=2.0.1

test:
  imports:
    - dtool_lookup_server_notification_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IMTEK-Simulation/dtool-lookup-server-notification-plugin
  summary: dtool lookup server plugin for receiving elastic-search update notifications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
